export const siteConfig = {
  name: 'BlockTodo',
  url: 'https://blocktodo-miniapp.vercel.app',
  description: 'Manage todo items onchain with create, toggle, delete, and live reads on Base.',
  ogTitle: 'BlockTodo | Onchain Todo Manager on Base',
  ogDescription: 'Create, complete, remove, and browse todo items from a live Base contract in a production-ready mini app.',
  ogImageUrl: 'https://blocktodo-miniapp.vercel.app/og.svg',
  iconUrl: 'https://blocktodo-miniapp.vercel.app/icon.svg',
  splashImageUrl: 'https://blocktodo-miniapp.vercel.app/splash.svg',
  screenshotUrls: [
    'https://blocktodo-miniapp.vercel.app/screenshot-1.svg',
    'https://blocktodo-miniapp.vercel.app/screenshot-2.svg',
    'https://blocktodo-miniapp.vercel.app/screenshot-3.svg',
  ],
  splashBackgroundColor: '#8ed8ff',
  primaryCategory: 'productivity',
  secondaryCategory: 'utility',
  subtitle: 'Sky-blue task control',
  tagline: 'Todo CRUD, anchored on Base',
  tags: ['productivity', 'utility', 'todo', 'base', 'onchain'],
  builderCode: '',
  builderCodeHex: '',
  builderOwnerAddress: '',
};
